# Generated by Django 4.2.6 on 2023-10-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_project_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
